config/routes.rb
Rails.application.routes.draw do
  resources :hotels
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  validates :name, :street, :suburb, :state, presence: true
end

app/models/hotel.rb
class Hotel < ApplicationRecord

  geocoded_by :full_street_address # can also be an IP address
  after_validation :geocode # auto-fetch coordinates

  def full_street_address
    [street, suburb, state, postcode, country].compact.join(',')
  end

  def self.search(search)
    where("name LIKE ?, suburb LIKE ?","%#{search}%, %#{search}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]

  # GET /hotels
  # GET /hotels.json
  def index
    if params[:search]
      @hotels = Hotel.near(params[:search], 1)
      # grabs the location coordinates of what ever you typed in the search and returns it into a array with latitude and longitude 0,1 respectively
      @location = Geocoder.coordinates(params[:search] )
    else
      @hotels = Hotel.all
    end
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1
  # PATCH/PUT /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url, notice: 'Hotel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hotel_params
      params.require(:hotel).permit(:name, :street, :suburb, :state, :postcode, :country)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_form.html.erb
<%= simple_form_for(@hotel) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :street %>
    <%= f.input :suburb %>
    <%= f.input :state, collection: ['NSW', 'QLD', 'VIC', 'WA', 'SA', 'NT'], as: :radio_buttons %>
    <%= f.input :postcode %>
    <%= f.input :country, priority: ['Australia', 'New Zealand'] %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/hotels/edit.html.erb
<h1>Editing Hotel</h1>

<%= render 'form', hotel: @hotel %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>

app/views/hotels/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag(hotels_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search" %>
<%= submit_tag "Search" %>
<% end %>

<!-- <% if @hotel.present? %>
  <%= @hotel %>
<% else %>
  <p>The are no Hotels matching <%= params[:search] %>.</p>
<% end %> -->

<h1>Hotels</h1>

<div id="map"></div>



<script>

function initMap() {

  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 14,
    <% if @location %>
    // dumps the hased values of @location [0]=lat [1]=lng as coordinates are thrown in a array by Geocoder
    center: {lat: <%= @location[0] %>, lng: <%= @location[1] %> }
    <% else %>
    center: {lat: -63.8798834333333, lng: 400.200380133333}
    <% end %>
  });

  <% @hotels.each_with_index do |hotel, index| %>
  var myLatLng<%= index %> = {lat: <%= hotel.latitude %>, lng: <%= hotel.longitude %> };

  var contentString<%= index %> = '<%= hotel.name %>';

     var infowindow<%= index %> = new google.maps.InfoWindow({
       content: contentString<%= index %>
     });

  var marker<%= index %> = new google.maps.Marker({
    position: myLatLng<%= index %>,
    map: map,
    title: '<%= hotel.name %>'
  });

  marker<%= index %>.addListener('click', function() {
            infowindow<%= index %>.open(map, marker<%= index %>);
          });
  <% end %>
}
</script>

    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCR1FSyuTsZCBcx0qVf95FvbNPm8ru9CRc&callback=initMap">
    </script>


<table>

  <thead>
    <tr>
      <th>Name</th>
      <th>Street</th>
      <th>Suburb</th>
      <th>State</th>
      <th>Postcode</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hotels.each do |hotel| %>
      <tr>
        <td><%= hotel.name %></td>
        <td><%= hotel.street %></td>
        <td><%= hotel.suburb %></td>
        <td><%= hotel.state %></td>
        <td><%= hotel.postcode %></td>
        <td><%= hotel.country %></td>
        <td><%= link_to 'Show', hotel %></td>
        <td><%= link_to 'Edit', edit_hotel_path(hotel) %></td>
        <td><%= link_to 'Destroy', hotel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hotel', new_hotel_path %>

app/views/hotels/new.html.erb
<h1>New Hotel</h1>

<%= render 'form', hotel: @hotel %>

<%= link_to 'Back', hotels_path %>

app/views/hotels/search.html.erb
<div id="map"></div>



<script>

function initMap() {

  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 14,

    <% if @location %>
    // dumps the hased values of @location [0]=lat [1]=lng as coordinates are thrown in a array by Geocoder
    center: {lat: <%=@location[0]%>, lng: <%=@location[1]%>}
    <% else %>
    center: {lat: -33.8798834333333, lng: 151.200380133333}
    <% end %>
  });

  <% @hotels.each_with_index do |hotel, index| %>
  var myLatLng<%= index %> = {lat: <%= hotel.latitude %>, lng: <%= hotel.longitude %> };

  var contentString<%= index %> = '<%= hotel.name %>';

     var infowindow<%= index %> = new google.maps.InfoWindow({
       content: contentString<%= index %>
     });

  var marker<%= index %> = new google.maps.Marker({
    position: myLatLng<%= index %>,
    map: map,
    title: '<%= hotel.name %>'
  });

  marker<%= index %>.addListener('click', function() {
            infowindow<%= index %>.open(map, marker<%= index %>);
          });
  <% end %>
}
</script>

    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCR1FSyuTsZCBcx0qVf95FvbNPm8ru9CRc&callback=initMap">
    </script>

app/views/hotels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hotel.name %>
</p>

<p>
  <strong>Street:</strong>
  <%= @hotel.street %>
</p>

<p>
  <strong>Suburb:</strong>
  <%= @hotel.suburb %>
</p>

<p>
  <strong>State:</strong>
  <%= @hotel.state %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @hotel.postcode %>
</p>

<p>
  <strong>Country:</strong>
  <%= @hotel.country %>
</p>


<%= link_to 'Edit', edit_hotel_path(@hotel) %> |
<%= link_to 'Back', hotels_path %>

<div id="map"></div>
<script>

function initMap() {
  var myLatLng = {lat: <%= @hotel.latitude %>, lng: <%= @hotel.longitude %> };

  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 15,
    center: myLatLng
  });

  var marker = new google.maps.Marker({
    position: myLatLng,
    map: map,
    title: '<%= @hotel.name %>'
  });
}
</script>
<script async defer
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCR1FSyuTsZCBcx0qVf95FvbNPm8ru9CRc&callback=initMap">
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotelfinder</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
     <%= debug(params) if Rails.env.development? %>
  </body>
</html>